language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "9"
  - "8"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
