addons:
  chrome: 'stable'
  firefox: 'latest'
before_script:
  - npm run lint
cache:
  directories:
    - node_modules
dist: trusty
install:
  - npm install
language: node_js
node_js:
  - '14'
  - '12'
script:
  - xvfb-run npm run test
  - npm run report-coverage
sudo: required
