language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "12"
  - "11"
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - npm run report-coverage
